baseURL = "https://test-hugo.netlify.app"
title = "MR. Mukles CMS"
theme = "bigspring-light-hugo"
paginate = "3"
summaryLength = "15"
disqusShortname = ""
googleAnalytics = ""

[markup.goldmark.renderer]
unsafe = true
