logo = ""
logo_width = "200px"
description = "This is meta description"
author = "Themefisher"
image = "images/logo.png"
contact_form_action = "#"
blogCategoryType = "category"

[preloader]
enable = false
preloader = ""

[navigation_button]
enable = true
label = "Get Started"
link = "contact"

[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

[[social]]
title = "facebook"
icon = "fab fa-facebook"
link = "#"

[[social]]
title = "twitter"
icon = "fab fa-twitter"
link = "#"

[[social]]
title = "skype"
icon = "fab fa-skype"
link = "#"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin"
link = "#"
